version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_ENV=development
  # todo not yet needed for now, used when have api routes
  # database:
  #   image: postgres:15
  #   container_name: database
  #   env_file:
  #     - .env
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   networks:
  #     - mson_project

  nginx:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
    networks:
      - mson_project

volumes:
  db_data:

networks:
  mson_project:
    driver: bridge
